# -*- coding: utf-8 -*-
"""
游戏配置文件
包含所有游戏常量和配置参数
"""

# 屏幕设置
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# 颜色定义 (R, G, B)
COLOR_BLACK_XZH = (0, 0, 0)
COLOR_WHITE_XZH = (255, 255, 255)
COLOR_RED_XZH = (255, 0, 0)
COLOR_GREEN_XZH = (0, 255, 0)
COLOR_BLUE_XZH = (0, 0, 255)
COLOR_YELLOW_XZH = (255, 255, 0)
COLOR_ORANGE_XZH = (255, 165, 0)
COLOR_PURPLE_XZH = (160, 32, 240)
COLOR_CYAN_XZH = (0, 255, 255)
COLOR_GRAY_XZH = (128, 128, 128)

# 挡板设置
PADDLE_WIDTH_DEFAULT_XZH = 130  # 增加初始挡板长度
PADDLE_WIDTH_MIN_XZH = 30  # 最小挡板长度
PADDLE_WIDTH_MAX_XZH = 150
PADDLE_HEIGHT_XZH = 15
PADDLE_SPEED_XZH = 7  # 初始移动速度
PADDLE_SPEED_MAX_XZH = 15  # 最大移动速度
PADDLE_COLOR_XZH = COLOR_BLUE_XZH

# 球设置
BALL_RADIUS_XZH = 8
BALL_SPEED_DEFAULT_XZH = 5
BALL_SPEED_MIN_XZH = 3
BALL_SPEED_MAX_XZH = 10
BALL_COLOR_XZH = COLOR_WHITE_XZH

# 砖块设置
BRICK_ROWS_XZH = 5
BRICK_COLS_XZH = 10
BRICK_WIDTH_XZH = 75
BRICK_HEIGHT_XZH = 30
BRICK_PADDING_XZH = 5
BRICK_OFFSET_TOP_XZH = 60
BRICK_OFFSET_LEFT_XZH = 35

# 砖块颜色配置（不同行不同颜色）
BRICK_COLORS_XZH = [
    COLOR_RED_XZH,
    COLOR_ORANGE_XZH,
    COLOR_YELLOW_XZH,
    COLOR_GREEN_XZH,
    COLOR_CYAN_XZH
]

# 游戏设置
INITIAL_LIVES_XZH = 3
POINTS_PER_BRICK_XZH = 10

# 难度调整参数
DIFFICULTY_CHECK_INTERVAL_XZH = 3  # 每击中3块砖块检查一次难度
HIT_RATE_THRESHOLD_HIGH_XZH = 0.50  # 命中率高于50%增加难度
PADDLE_WIDTH_ADJUSTMENT_XZH = 3  # 挡板宽度调整幅度（每次缩短3像素）
PADDLE_SPEED_ADJUSTMENT_XZH = 0.3  # 挡板速度调整幅度（每次增加0.3）

# 游戏模式
MODE_CLASSIC_XZH = "classic"  # 经典模式
MODE_CHALLENGE_XZH = "challenge"  # 挑战模式

# 挑战模式特殊设置
CHALLENGE_LIVES_XZH = 5  # 挑战模式初始生命值
CHALLENGE_BRICK_ROWS_XZH = 8  # 挑战模式砖块行数
CHALLENGE_SPEED_MULTIPLIER_XZH = 1.5  # 挑战模式速度倍率

# 数据文件路径
DATA_FILE_PATH_XZH = "data.json"
REPORT_IMAGE_PATH_XZH = "player_report.png"

# 字体设置
FONT_SIZE_LARGE_XZH = 48
FONT_SIZE_MEDIUM_XZH = 32
FONT_SIZE_SMALL_XZH = 24
